development:
  clients:
    default:
      database: sin_product_review_development
      hosts:
        - localhost:27017


test:
  clients:
    default:
      database: sin_product_review_test
      hosts:
        - localhost:27017
      options:
        consistency: strong

production:
  clients:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
    username: <%= ENV['MONGOHQ_USERNAME'] %>
    password: <%= ENV['MONGOHQ_PASSWORD'] %>
    database: sin_dictionary_production
    options:
      skip_version_check: true
      safe: true
      consistency: strong